version: 2

models:
  - name: fct_orders
    columns:
      - name: customer_id
        data_tests:
          - relationships:
              field: customer_id
              to: ref('stg_jaffle_shop__customers')
  - name: dim_customers
    description: One record per customer
    columns:
      - name: customer_id
        description: Primary key
        data_tests:
          - unique
          - not_null
      - name: first_order_date
        description: NULL when a customer has not yet placed an order.
